### ISSUE TITLE
Allows corrupted Tracking Data Directory to be opened / fixed from `fort-studio` / `fort-myrmidon`

### ISSUE THREAD

**Issue by atuleu** [formicidae-tracker/myrmidon#219]
**Is your feature request related to a problem? Please describe.**
With the FORT system, it may quite often happens that a tracking data directory becomes corrupted... Indeed, often user ran out of disk space during acquisition

**Describe the solution you'd like**
When opening a tracking data directory, any error should be reported with exception that allow the error to be fixed by modifying the data. `fort-studio` could display these error / fixes and allow the user to react accordingly.

**Comment by atuleu** [comment]
* [ ]: Create a FixableError public exception. It should describe the problem, describe the fix, and implement the fix
* [ ]: Makes priv::TrackingDataDirectory to softly ignore FixableError, but return them. It means, it should try to open every TagCloseUp, but do not do so already
* [ ]: Makes fort::myrmidon::Experiment::TrackingDataDirectory return a list of fixable error
