### ISSUE TITLE
Python bindings tracking solver CollideFrame raises ValueError

### ISSUE THREAD

**Issue by matthiasruegg** [formicidae-tracker/myrmidon#252]
**Describe the bug**
The Python bindings tracking solver raises a ValueError: zone ID 0 not known, although a zone with this ID is defined.

**Minimal example**
```
import py_fort_myrmidon as fm
import py_fort_hermes as fh

f_myrmidon = 'testdata.myrmidon'
solver = fm.Experiment.OpenDataLess(f_myrmidon).CompileTrackingSolver()
ro = fh.FrameReadout()
frame = solver.IdentifyFrame(ro, 0)
collisions = solver.CollideFrame(frame)
```
yields:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Unknown SpaceID 0 in IdentifiedFrame
```

**Affected packages**
Please select one or more package by putting a `x` in the brackets

- [ ] `libfort-myrmidon` installed from `conda`
- [x ] `py_fort_myrmidon`installed from `conda` test channel
- [ ] `r-fort-myrmidon` installed from `conda`
- [ ] `fort-studio` installed from  `snap`
- [ ] `fort-studio` installed from `conda`

**Installed version**
```
# Name                    Version                   Build  Channel
py-fort-myrmidon          0.8.3           6_h1234567_g92e3bd91    formicidae-tracker/label/test
```

**Additional context**
As far as I can see, the exception is thrown by the AntZoner of the CollisionSolver. The collision solver seems to be unaware of any defined zones (``` d_spaceDefinitions.count(frame.Space) == 0 ```).

**Comment by atuleu** [comment]
In `myrmidon` ID starts at index `1`. Index `0` is reserved for `any/no object`. Also you should make sure your experiment contains at least (potentially empty) space.
